import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import Navbar from "@/components/NavBar";
// import "./css/card.scss";
import "./css/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={``}
      >
                <main className="min-h-screen relative mx-auto px-6 sm:px-12 lg:max-w-[70rem] xl:max-w-[76rem] 2xl:max-w-[92rem]">

                {/* <ToastContainer /> */}

      <Navbar/>
        {children}
        </main>

      </body>
    </html>
  );
}
